# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub (luisenalvar)'
        repository: 'luisenalvar/aztfweatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
## Terraform Task 
## Disable for now

# - stage: Deploy  
#   displayName: 'Azure Provision of Resources ...'
#   dependsOn: Build
#   jobs:
#   - job: AppDeployment 
#     displayName: 'Create a App Container Instance'
#     pool:
#       vmImage: ubuntu-latest
#     variables:
#     - group: TerraformServicePrincipalEnvVars
#     steps:
#     - script: |
#         set -e
#         terraform init -input=false
#         terraform apply -input=false -auto-approve
#       name: Terraform 
#       displayName: 'Running Terraform  ...'
#       env:
#         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
#         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
#         ARM_TENANT_ID: $(ARM_TENANT_ID)
#         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
#         TF_VAR_imagebuild: $(tag)